#
# https://github.com/generaliinformatik/ansible_role_ec2
# (c) 2019 Generali Informatik
#

- name: register instance_facts by name
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ name }}"
  register: instance_facts

