#
# https://github.com/generaliinformatik/ansible_role_ec2
# (c) 2019 Generali Deutschland Informatik Services GmbH
#

- import_tasks: stat_instance_ids_file.yml
- name: halt if file is missing
  fail:
    msg: missing file {{ instance_ids_file.stat.path }}
  when:
    - not instance_ids_file.stat.exists
- name: load file content
  command: cat {{ instance_ids_file.stat.path }}
  register: cat
- name: set instance ids from file
  set_fact:
    instance_ids: "{{ cat.stdout | from_json }}"
